# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1415bd14381b0d6d0d0d9b54e6060ac9eeb91e82ac128431d31a30662d9758a8c0dcb54175012adc2a87dc5f03603623c28f7da69c61955d30920d9afb4e3217

test:
  secret_key_base: de99c20c68f0b1c43d81ffb8b628c3b7f7a16f50be3d4f0238ab65973959a2ff272725d25d793036244c3ba8640ad0c56020e43177b02855276ac3320a67edb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
